# -*- coding: utf-8 -*-
"""LinearRegression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16jrToj9n2V6vugyUJWR4uYGwbI0H5eB4
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

#Create Dataset
data ={'Experience':[1,2,3,4,5],'Salary':[20000,40000,60000,80000,100000]}
df = pd.DataFrame(data)

#Define x and y
x=df[['Experience']]
y=df['Salary']

model=LinearRegression()
model.fit(x,y)

#Step 5
y_pred=model.predict(x)

salary=model.predict([[10]])
print("Preedicted Salary for 10 years of Experience=Rs",round(salary[0],2))

#calculate error
error=y_pred

#calculate Squared Residuals