# -*- coding: utf-8 -*-
"""LinearRegression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/sangeethaatg-make/First/blob/main/LinearRegression.ipynb
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

#Create Dataset
data ={'Experience':[1,2,3,4,5],'Salary':[20000,40000,60000,80000,100000]}
df = pd.DataFrame(data)

#Define x and y
x=df[['Experience']]
y=df['Salary']

model=LinearRegression()
model.fit(x,y)

#Step 5
y_pred=model.predict(x)

st.title("Salary Prediction App")

experience = st.number_input("Enter Years of Experience", min_value=0.0)

if st.button("Predict Salary"):
    prediction = model.predict(pd.DataFrame({"Experience": [experience]}))
    st.success(f"Predicted Salary: ₹{prediction[0]:,.2f}")



#calculate Squared Residuals